name: CMake_Windows_MSVC

on: 
  push:        
  pull_request:
    branches:
    - main

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: "CS230 Project3"

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    timeout-minutes: 5

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: actions/checkout@v4

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: CTest
      id: ctest
      shell: bash
      run: ctest --test-dir build --build-config Release

    - name: Rerun Failed Tests with Output
      if: steps.ctest.outcome == 'failure'
      shell: bash
      run: ctest --test-dir build --build-config Release --rerun-failed --output-on-failure