name: CMake_Windows_MSVC

on: 
  push:        
  pull_request:
    branches:
    - main

jobs:
  build-windows:
    runs-on: windows-latest

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    timeout-minutes: 5

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: CTest
      shell: bash
      run: ctest --build-config Release